import type React from 'react';

const base: React.CSSProperties = {
  fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
  fontSize: '13.5px',
  lineHeight: '1.65',
  direction: 'ltr',
  textAlign: 'left',
  whiteSpace: 'pre',
  wordSpacing: 'normal',
  wordBreak: 'normal',
  wordWrap: 'normal',
  tabSize: 4,
  hyphens: 'none',
};

export const darkTheme: Record<string, React.CSSProperties> = {
  'code[class*="language-"]': { ...base, color: '#e2e8f0', background: 'none' },
  'pre[class*="language-"]': { ...base, color: '#e2e8f0', background: 'transparent', padding: '20px', margin: '0', overflow: 'auto', borderRadius: '0' },
  comment: { color: '#64748b', fontStyle: 'italic' },
  prolog: { color: '#64748b' },
  doctype: { color: '#64748b' },
  cdata: { color: '#64748b' },
  punctuation: { color: '#94a3b8' },
  property: { color: '#00ADD8' },
  tag: { color: '#00ADD8' },
  boolean: { color: '#F59E0B' },
  number: { color: '#F59E0B' },
  constant: { color: '#F59E0B' },
  symbol: { color: '#F59E0B' },
  deleted: { color: '#EF4444' },
  selector: { color: '#10B981' },
  'attr-name': { color: '#10B981' },
  string: { color: '#10B981' },
  char: { color: '#10B981' },
  builtin: { color: '#10B981' },
  inserted: { color: '#10B981' },
  operator: { color: '#94a3b8' },
  entity: { color: '#F59E0B' },
  url: { color: '#00ADD8' },
  variable: { color: '#e2e8f0' },
  atrule: { color: '#00ADD8' },
  'attr-value': { color: '#10B981' },
  function: { color: '#00ADD8' },
  'class-name': { color: '#F59E0B' },
  keyword: { color: '#c792ea' },
  regex: { color: '#F59E0B' },
  important: { color: '#F59E0B', fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};

export const lightTheme: Record<string, React.CSSProperties> = {
  'code[class*="language-"]': { ...base, color: '#1E293B', background: 'none' },
  'pre[class*="language-"]': { ...base, color: '#1E293B', background: 'transparent', padding: '20px', margin: '0', overflow: 'auto', borderRadius: '0' },
  comment: { color: '#8B95A5', fontStyle: 'italic' },
  prolog: { color: '#8B95A5' },
  doctype: { color: '#8B95A5' },
  cdata: { color: '#8B95A5' },
  punctuation: { color: '#4B5563' },
  property: { color: '#0068A8' },
  tag: { color: '#0068A8' },
  boolean: { color: '#9D3E0C' },
  number: { color: '#1750EB' },
  constant: { color: '#1750EB' },
  symbol: { color: '#1750EB' },
  deleted: { color: '#C41A16' },
  selector: { color: '#067D17' },
  'attr-name': { color: '#067D17' },
  string: { color: '#067D17' },
  char: { color: '#067D17' },
  builtin: { color: '#067D17' },
  inserted: { color: '#067D17' },
  operator: { color: '#4B5563' },
  entity: { color: '#9D3E0C' },
  url: { color: '#0068A8' },
  variable: { color: '#1E293B' },
  atrule: { color: '#0068A8' },
  'attr-value': { color: '#067D17' },
  function: { color: '#0068A8' },
  'class-name': { color: '#9D3E0C' },
  keyword: { color: '#7C3AED' },
  regex: { color: '#9D3E0C' },
  important: { color: '#9D3E0C', fontWeight: 'bold' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};

export const editorDarkTheme: Record<string, React.CSSProperties> = {
  ...darkTheme,
  'pre[class*="language-"]': { ...base, color: '#e2e8f0', background: 'transparent', padding: '0', margin: '0', overflow: 'visible', borderRadius: '0' },
};

export const editorLightTheme: Record<string, React.CSSProperties> = {
  ...lightTheme,
  'pre[class*="language-"]': { ...base, color: '#1E293B', background: 'transparent', padding: '0', margin: '0', overflow: 'visible', borderRadius: '0' },
};
